# ==============================
# APPLICATION
# ==============================
spring.application.name=task-management-system

# ==============================
# DATASOURCE
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/your_db
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# FLYWAY
# ==============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ==============================
# SERVER
# ==============================
server.port=8080
server.servlet.context-path=/api

# ==============================
# SWAGGER / OPENAPI
# ==============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha

# ==============================
# LOGGING
# ==============================
logging.level.com.echt.task_management_system=DEBUG
logging.level.org.hibernate.SQL=INFO